/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef TRUST_H
#define TRUST_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace trust {

class Trust : public RapidNetApplicationBase
{
public:
  static const string EPRETURN;
  static const string EPROVQUERY;
  static const string ERRETURN;
  static const string ERULEQUERY;
  static const string EMUTUALTRUSTPATH;
  static const string EMUTUALTRUSTPATHDELETE;
  static const string EMUTUALTRUSTPATHTEMP;
  static const string EMUTUALTRUSTPATHTEMPDELETE;
  static const string ESHARESULT;
  static const string ESHARESULTDELETE;
  static const string ESHARESULTTEMP;
  static const string ESHARESULTTEMPDELETE;
  static const string ETRUSTEVENT;
  static const string ETRUSTEVENTDELETE;
  static const string ETRUSTEVENTTEMP;
  static const string ETRUSTEVENTTEMPDELETE;
  static const string ETRUSTPATH;
  static const string ETRUSTPATHDELETE;
  static const string ETRUSTPATHTEMP;
  static const string ETRUSTPATHTEMPDELETE;
  static const string MUTUALTRUSTPATH;
  static const string PITERATE;
  static const string PQLIST;
  static const string PRESULTTMP;
  static const string PRETURN;
  static const string PROV;
  static const string PROVQUERY;
  static const string RITERATE;
  static const string RQLIST;
  static const string RRESULTTMP;
  static const string RRETURN;
  static const string RULEEXEC;
  static const string RULEQUERY;
  static const string SHARESULT;
  static const string TRUST;
  static const string TRUSTEVENT;
  static const string TRUSTPATH;

  static TypeId GetTypeId (void);

  Trust ();

  virtual ~Trust ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void Prov_ra_1Eca0Ins (Ptr<Tuple> trustPath);

  virtual void Prov_ra_1Eca0Del (Ptr<Tuple> trustPath);

  virtual void Prov_ra_2_ecaAdd (Ptr<Tuple> etrustEventTemp);

  virtual void Prov_ra_2_ecaDel (Ptr<Tuple> etrustEventTempDelete);

  virtual void Prov_ra_3_ecaAdd (Ptr<Tuple> etrustEventTemp);

  virtual void Prov_ra_3_ecaDel (Ptr<Tuple> etrustEventTempDelete);

  virtual void Prov_ra_4_ecaAdd (Ptr<Tuple> etrustEvent);

  virtual void Prov_ra_4_ecaDel (Ptr<Tuple> etrustEventDelete);

  virtual void Prov_ra_5_ecaAdd (Ptr<Tuple> etrustEvent);

  virtual void Prov_ra_5_ecaDel (Ptr<Tuple> etrustEventDelete);

  virtual void Prov_r1_1Eca0Ins (Ptr<Tuple> trust);

  virtual void Prov_r1_1Eca0Del (Ptr<Tuple> trust);

  virtual void Prov_r1_2_ecaAdd (Ptr<Tuple> etrustPathTemp);

  virtual void Prov_r1_2_ecaDel (Ptr<Tuple> etrustPathTempDelete);

  virtual void Prov_r1_3_ecaAdd (Ptr<Tuple> etrustPathTemp);

  virtual void Prov_r1_3_ecaDel (Ptr<Tuple> etrustPathTempDelete);

  virtual void Prov_r1_4_ecaAdd (Ptr<Tuple> etrustPath);

  virtual void Prov_r1_4_ecaDel (Ptr<Tuple> etrustPathDelete);

  virtual void Prov_r1_5_ecaAdd (Ptr<Tuple> etrustPath);

  virtual void Prov_r1_5_ecaDel (Ptr<Tuple> etrustPathDelete);

  virtual void Prov_r2_1Eca0Ins (Ptr<Tuple> trust);

  virtual void Prov_r2_1Eca0Del (Ptr<Tuple> trust);

  virtual void Prov_r2_1Eca3Ins (Ptr<Tuple> trustPath);

  virtual void Prov_r2_1Eca3Del (Ptr<Tuple> trustPath);

  virtual void Prov_r3_1Eca0Ins (Ptr<Tuple> trustEvent);

  virtual void Prov_r3_1Eca0Del (Ptr<Tuple> trustEvent);

  virtual void Prov_r3_1Eca3Ins (Ptr<Tuple> trustPath);

  virtual void Prov_r3_1Eca3Del (Ptr<Tuple> trustPath);

  virtual void Prov_r3_2_ecaAdd (Ptr<Tuple> emutualTrustPathTemp);

  virtual void Prov_r3_2_ecaDel (Ptr<Tuple> emutualTrustPathTempDelete);

  virtual void Prov_r3_3_ecaAdd (Ptr<Tuple> emutualTrustPathTemp);

  virtual void Prov_r3_3_ecaDel (Ptr<Tuple> emutualTrustPathTempDelete);

  virtual void Prov_r3_4_ecaAdd (Ptr<Tuple> emutualTrustPath);

  virtual void Prov_r3_4_ecaDel (Ptr<Tuple> emutualTrustPathDelete);

  virtual void Prov_r3_5_ecaAdd (Ptr<Tuple> emutualTrustPath);

  virtual void Prov_r3_5_ecaDel (Ptr<Tuple> emutualTrustPathDelete);

  virtual void Prov_r4_1Eca0Ins (Ptr<Tuple> trust);

  virtual void Prov_r4_1Eca0Del (Ptr<Tuple> trust);

  virtual void Prov_r4_2_ecaAdd (Ptr<Tuple> eshaResultTemp);

  virtual void Prov_r4_2_ecaDel (Ptr<Tuple> eshaResultTempDelete);

  virtual void Prov_r4_3_ecaAdd (Ptr<Tuple> eshaResultTemp);

  virtual void Prov_r4_3_ecaDel (Ptr<Tuple> eshaResultTempDelete);

  virtual void Prov_r4_4_ecaAdd (Ptr<Tuple> eshaResult);

  virtual void Prov_r4_4_ecaDel (Ptr<Tuple> eshaResultDelete);

  virtual void Prov_r4_5_ecaAdd (Ptr<Tuple> eshaResult);

  virtual void Prov_r4_5_ecaDel (Ptr<Tuple> eshaResultDelete);

  virtual void Prov_r5_1Eca0Ins (Ptr<Tuple> trustPath);

  virtual void Prov_r5_1Eca0Del (Ptr<Tuple> trustPath);

  virtual void Prov_r6_1Eca0Ins (Ptr<Tuple> trustEvent);

  virtual void Prov_r6_1Eca0Del (Ptr<Tuple> trustEvent);

  virtual void Prov_r7_1Eca0Ins (Ptr<Tuple> mutualTrustPath);

  virtual void Prov_r7_1Eca0Del (Ptr<Tuple> mutualTrustPath);

  virtual void Prov_edb_1Eca1Ins (Ptr<Tuple> trust);

  virtual void Prov_edb_1Eca1Del (Ptr<Tuple> trust);

  virtual void Edb1_eca (Ptr<Tuple> provQuery);

  virtual void Idb1a_eca (Ptr<Tuple> provQuery);

  virtual void Idb1b_eca (Ptr<Tuple> provQuery);

  virtual void Idb2_eca (Ptr<Tuple> provQuery);

  virtual void Idb3_eca (Ptr<Tuple> provQuery);

  virtual void Idb4_eca (Ptr<Tuple> pIterate);

  virtual void Idb5_eca (Ptr<Tuple> pIterate);

  virtual void Idb6a_eca (Ptr<Tuple> eRuleQuery);

  virtual void Idb7_eca (Ptr<Tuple> rReturn);

  virtual void Idb8Eca0Ins (Ptr<Tuple> pResultTmp);

  virtual void Idb8Eca1Ins (Ptr<Tuple> pQList);

  virtual void Idb9_eca (Ptr<Tuple> ePReturn);

  virtual void Rv1_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv2_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv3_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv4_eca (Ptr<Tuple> rIterate);

  virtual void Rv5_eca (Ptr<Tuple> rIterate);

  virtual void Rv6_eca (Ptr<Tuple> eProvQuery);

  virtual void Rv7_eca (Ptr<Tuple> pReturn);

  virtual void Rv8Eca0Ins (Ptr<Tuple> rResultTmp);

  virtual void Rv8Eca1Ins (Ptr<Tuple> rQList);

  virtual void Rv9_eca (Ptr<Tuple> eRReturn);

};

} // namespace trust
} // namespace rapidnet
} // namespace ns3

#endif // TRUST_H
