## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('trust', ['internet-stack'])
    module.source = [
        'trust.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'trust'
    headers.source = [
        'trust.h',
        'trust-helper.h',
        ]
