/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef HYPERTEXTCLASSQUERY_H
#define HYPERTEXTCLASSQUERY_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace hypertextclassquery {

class HyperTextClassQuery : public RapidNetApplicationBase
{
public:
  static const string PRETURN;
  static const string PROVQUERY;
  static const string RECORDS;
  static const string TUPLE;

  static TypeId GetTypeId (void);

  HyperTextClassQuery ();

  virtual ~HyperTextClassQuery ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void Q1Eca0Ins (Ptr<Tuple> tuple);

  virtual void Q2_eca (Ptr<Tuple> pReturn);

};

} // namespace hypertextclassquery
} // namespace rapidnet
} // namespace ns3

#endif // HYPERTEXTCLASSQUERY_H
