## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('smoke', ['internet-stack'])
    module.source = [
        'smoke.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'smoke'
    headers.source = [
        'smoke.h',
        'smoke-helper.h',
        ]
