/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef HYPERTEXTCLASS_H
#define HYPERTEXTCLASS_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace hypertextclass {

class HyperTextClass : public RapidNetApplicationBase
{
public:
  static const string EPRETURN;
  static const string EPROVQUERY;
  static const string ERRETURN;
  static const string ERULEQUERY;
  static const string ESHARESULT;
  static const string ESHARESULTDELETE;
  static const string ESHARESULTTEMP;
  static const string ESHARESULTTEMPDELETE;
  static const string ETOPIC;
  static const string ETOPICDELETE;
  static const string ETOPICTEMP;
  static const string ETOPICTEMPDELETE;
  static const string HASWORD;
  static const string LINKS;
  static const string PITERATE;
  static const string PQLIST;
  static const string PRESULTTMP;
  static const string PRETURN;
  static const string PROV;
  static const string PROVQUERY;
  static const string RITERATE;
  static const string RQLIST;
  static const string RRESULTTMP;
  static const string RRETURN;
  static const string RULEEXEC;
  static const string RULEQUERY;
  static const string SHARESULT;
  static const string TOPIC;

  static TypeId GetTypeId (void);

  HyperTextClass ();

  virtual ~HyperTextClass ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void Prov_rl_1Eca0Ins (Ptr<Tuple> links);

  virtual void Prov_rl_1Eca0Del (Ptr<Tuple> links);

  virtual void Prov_rl_1Eca3Ins (Ptr<Tuple> topic);

  virtual void Prov_rl_1Eca3Del (Ptr<Tuple> topic);

  virtual void Prov_rl_2_ecaAdd (Ptr<Tuple> etopicTemp);

  virtual void Prov_rl_2_ecaDel (Ptr<Tuple> etopicTempDelete);

  virtual void Prov_rl_3_ecaAdd (Ptr<Tuple> etopicTemp);

  virtual void Prov_rl_3_ecaDel (Ptr<Tuple> etopicTempDelete);

  virtual void Prov_rl_4_ecaAdd (Ptr<Tuple> etopic);

  virtual void Prov_rl_4_ecaDel (Ptr<Tuple> etopicDelete);

  virtual void Prov_rl_5_ecaAdd (Ptr<Tuple> etopic);

  virtual void Prov_rl_5_ecaDel (Ptr<Tuple> etopicDelete);

  virtual void Prov_r0_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r0_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r1_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r1_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r2_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r2_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r3_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r3_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r4_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r4_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r5_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r5_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r6_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r6_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r7_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r7_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r8_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r8_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r9_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r9_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r10_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r10_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r11_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r11_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r12_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r12_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r13_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r13_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r14_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r14_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r15_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r15_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r16_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r16_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r17_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r17_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r18_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r18_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r19_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r19_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r20_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r20_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r21_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r21_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r22_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r22_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r23_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r23_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r24_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r24_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r25_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r25_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r26_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r26_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r27_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r27_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r28_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r28_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r29_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r29_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r30_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r30_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r31_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r31_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r32_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r32_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r33_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r33_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r34_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r34_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r35_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r35_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r36_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r36_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r37_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r37_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r38_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r38_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r39_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r39_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r40_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r40_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r41_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r41_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r42_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r42_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r43_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r43_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r44_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r44_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r45_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r45_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r46_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r46_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r47_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r47_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r48_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r48_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r49_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r49_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r50_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r50_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r51_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r51_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r52_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r52_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r53_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r53_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r54_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r54_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r55_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r55_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r56_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r56_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r57_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r57_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r58_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r58_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r59_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r59_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r60_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r60_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r61_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r61_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r62_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r62_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r63_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r63_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r64_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r64_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r65_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r65_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r66_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r66_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r67_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r67_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r68_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r68_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r69_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r69_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r70_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r70_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r71_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r71_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r72_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r72_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r73_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r73_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r74_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r74_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r75_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r75_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r76_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r76_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r77_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r77_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r78_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r78_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r79_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r79_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r80_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r80_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r81_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r81_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r82_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r82_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r83_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r83_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r84_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r84_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r85_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r85_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r86_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r86_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r87_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r87_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r88_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r88_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r89_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r89_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r90_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r90_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r91_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r91_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r92_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r92_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r93_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r93_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r94_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r94_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r95_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r95_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r96_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r96_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r97_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r97_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r98_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r98_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r99_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r99_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r100_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r100_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r101_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r101_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r102_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r102_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r103_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r103_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r104_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r104_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r105_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r105_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r106_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r106_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r107_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r107_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r108_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r108_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r109_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r109_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r110_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r110_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r111_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r111_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r112_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r112_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r113_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r113_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r114_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r114_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r115_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r115_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r116_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r116_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r117_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r117_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r118_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r118_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r119_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r119_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r120_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r120_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r121_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r121_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r122_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r122_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r123_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r123_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r124_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r124_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r125_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r125_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r126_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r126_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r127_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r127_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r128_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r128_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r129_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r129_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r130_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r130_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r131_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r131_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r132_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r132_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r133_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r133_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r134_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r134_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r135_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r135_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r136_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r136_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r137_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r137_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r138_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r138_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r139_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r139_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r140_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r140_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r141_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r141_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r142_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r142_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r143_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r143_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r144_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r144_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r145_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r145_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r146_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r146_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r147_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r147_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r148_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r148_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r149_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r149_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r150_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r150_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r151_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r151_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r152_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r152_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r153_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r153_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r154_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r154_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r155_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r155_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r156_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r156_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r157_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r157_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r158_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r158_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r159_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r159_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r160_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r160_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r161_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r161_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r162_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r162_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r163_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r163_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r164_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r164_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r165_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r165_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r166_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r166_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r167_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r167_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r168_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r168_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r169_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r169_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r170_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r170_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r171_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r171_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r172_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r172_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r173_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r173_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r174_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r174_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r175_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r175_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r176_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r176_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r177_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r177_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r178_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r178_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r179_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r179_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r180_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r180_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r181_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r181_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r182_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r182_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r183_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r183_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r184_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r184_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r185_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r185_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r186_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r186_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r187_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r187_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r188_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r188_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r189_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r189_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r190_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r190_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r191_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r191_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r192_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r192_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r193_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r193_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r194_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r194_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r195_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r195_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r196_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r196_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r197_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r197_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r198_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r198_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r199_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r199_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r200_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r200_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r201_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r201_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r202_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r202_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r203_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r203_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r204_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r204_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r205_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r205_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r206_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r206_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r207_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r207_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r208_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r208_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r209_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r209_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r210_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r210_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r211_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r211_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r212_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r212_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r213_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r213_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r214_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r214_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r215_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r215_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r216_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r216_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r217_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r217_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r218_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r218_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r219_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r219_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r220_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r220_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r221_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r221_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r222_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r222_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r223_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r223_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r224_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r224_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r225_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r225_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r226_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r226_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r227_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r227_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r228_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r228_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r229_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r229_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r230_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r230_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r231_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r231_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r232_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r232_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r233_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r233_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r234_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r234_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r235_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r235_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r236_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r236_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r237_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r237_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r238_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r238_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r239_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r239_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r240_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r240_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r241_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r241_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r242_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r242_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r243_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r243_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r244_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r244_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r245_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r245_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r246_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r246_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r247_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r247_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r248_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r248_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r249_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r249_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r250_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r250_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r251_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r251_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r252_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r252_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r253_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r253_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r254_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r254_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r255_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r255_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r256_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r256_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r257_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r257_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r258_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r258_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r259_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r259_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r260_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r260_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r261_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r261_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r262_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r262_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r263_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r263_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r264_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r264_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r265_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r265_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r266_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r266_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r267_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r267_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r268_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r268_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r269_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r269_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r270_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r270_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r271_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r271_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r272_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r272_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r273_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r273_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r274_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r274_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r275_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r275_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r276_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r276_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r277_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r277_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r278_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r278_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r279_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r279_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r280_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r280_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r281_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r281_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r282_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r282_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r283_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r283_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r284_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r284_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r285_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r285_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r286_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r286_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r287_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r287_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r288_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r288_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r289_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r289_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r290_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r290_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r291_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r291_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r292_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r292_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r293_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r293_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r294_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r294_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r295_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r295_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r296_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r296_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r297_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r297_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r298_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r298_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r299_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r299_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r300_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r300_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r301_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r301_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r302_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r302_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r303_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r303_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r304_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r304_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r305_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r305_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r306_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r306_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r307_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r307_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r308_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r308_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r309_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r309_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r310_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r310_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r311_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r311_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r312_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r312_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r313_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r313_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r314_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r314_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r315_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r315_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r316_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r316_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r317_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r317_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r318_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r318_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r319_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r319_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r320_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r320_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r321_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r321_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r322_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r322_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r323_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r323_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r324_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r324_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r325_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r325_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r326_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r326_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r327_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r327_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r328_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r328_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r329_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r329_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r330_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r330_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r331_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r331_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r332_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r332_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r333_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r333_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r334_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r334_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r335_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r335_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r336_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r336_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r337_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r337_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r338_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r338_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r339_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r339_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r340_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r340_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r341_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r341_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r342_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r342_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r343_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r343_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r344_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r344_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r345_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r345_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r346_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r346_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r347_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r347_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r348_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r348_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r349_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r349_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r350_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r350_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r351_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r351_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r352_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r352_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r353_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r353_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r354_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r354_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r355_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r355_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r356_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r356_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r357_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r357_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r358_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r358_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r359_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r359_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r360_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r360_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r361_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r361_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r362_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r362_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r363_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r363_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r364_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r364_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r365_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r365_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r366_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r366_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r367_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r367_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r368_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r368_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r369_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r369_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r370_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r370_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r371_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r371_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r372_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r372_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r373_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r373_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r374_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r374_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r375_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r375_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r376_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r376_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r377_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r377_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r378_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r378_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r379_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r379_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r380_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r380_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r381_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r381_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r382_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r382_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r383_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r383_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r384_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r384_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r385_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r385_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r386_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r386_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r387_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r387_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r388_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r388_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r389_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r389_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r390_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r390_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r391_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r391_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r392_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r392_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r393_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r393_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r394_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r394_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r395_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r395_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r396_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r396_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r397_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r397_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r398_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r398_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r399_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r399_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r400_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r400_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r401_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r401_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r402_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r402_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r403_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r403_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r404_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r404_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r405_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r405_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r406_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r406_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r407_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r407_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r408_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r408_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r409_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r409_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r410_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r410_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r411_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r411_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r412_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r412_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r413_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r413_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r414_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r414_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r415_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r415_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r416_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r416_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r417_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r417_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r418_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r418_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r419_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r419_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r420_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r420_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r421_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r421_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r422_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r422_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r423_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r423_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r424_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r424_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r425_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r425_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r426_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r426_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r427_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r427_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r428_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r428_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r429_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r429_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r430_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r430_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r431_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r431_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r432_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r432_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r433_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r433_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r434_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r434_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r435_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r435_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r436_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r436_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r437_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r437_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r438_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r438_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r439_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r439_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r440_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r440_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r441_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r441_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r442_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r442_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r443_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r443_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r444_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r444_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r445_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r445_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r446_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r446_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r447_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r447_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r448_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r448_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r449_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r449_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r450_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r450_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r451_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r451_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r452_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r452_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r453_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r453_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r454_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r454_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r455_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r455_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r456_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r456_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r457_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r457_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r458_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r458_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r459_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r459_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r460_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r460_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r461_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r461_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r462_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r462_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r463_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r463_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r464_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r464_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r465_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r465_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r466_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r466_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r467_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r467_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r468_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r468_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r469_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r469_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r470_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r470_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r471_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r471_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r472_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r472_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r473_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r473_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r474_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r474_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r475_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r475_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r476_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r476_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r477_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r477_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r478_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r478_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r479_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r479_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r480_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r480_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r481_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r481_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r482_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r482_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r483_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r483_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r484_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r484_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r485_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r485_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r486_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r486_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r487_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r487_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r488_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r488_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r489_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r489_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r490_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r490_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r491_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r491_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r492_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r492_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r493_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r493_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r494_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r494_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r495_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r495_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r496_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r496_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r497_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r497_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r498_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r498_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_r499_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_r499_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_rs1_1Eca0Ins (Ptr<Tuple> topic);

  virtual void Prov_rs1_1Eca0Del (Ptr<Tuple> topic);

  virtual void Prov_rs1_2_ecaAdd (Ptr<Tuple> eshaResultTemp);

  virtual void Prov_rs1_2_ecaDel (Ptr<Tuple> eshaResultTempDelete);

  virtual void Prov_rs1_3_ecaAdd (Ptr<Tuple> eshaResultTemp);

  virtual void Prov_rs1_3_ecaDel (Ptr<Tuple> eshaResultTempDelete);

  virtual void Prov_rs1_4_ecaAdd (Ptr<Tuple> eshaResult);

  virtual void Prov_rs1_4_ecaDel (Ptr<Tuple> eshaResultDelete);

  virtual void Prov_rs1_5_ecaAdd (Ptr<Tuple> eshaResult);

  virtual void Prov_rs1_5_ecaDel (Ptr<Tuple> eshaResultDelete);

  virtual void Prov_rs2_1Eca0Ins (Ptr<Tuple> hasword);

  virtual void Prov_rs2_1Eca0Del (Ptr<Tuple> hasword);

  virtual void Prov_rs3_1Eca0Ins (Ptr<Tuple> links);

  virtual void Prov_rs3_1Eca0Del (Ptr<Tuple> links);

  virtual void Prov_edb_1Eca1Ins (Ptr<Tuple> hasword);

  virtual void Prov_edb_1Eca1Del (Ptr<Tuple> hasword);

  virtual void Prov_edb_2Eca1Ins (Ptr<Tuple> links);

  virtual void Prov_edb_2Eca1Del (Ptr<Tuple> links);

  virtual void Edb1_eca (Ptr<Tuple> provQuery);

  virtual void Idb1a_eca (Ptr<Tuple> provQuery);

  virtual void Idb1b_eca (Ptr<Tuple> provQuery);

  virtual void Idb2_eca (Ptr<Tuple> provQuery);

  virtual void Idb3_eca (Ptr<Tuple> provQuery);

  virtual void Idb4_eca (Ptr<Tuple> pIterate);

  virtual void Idb5_eca (Ptr<Tuple> pIterate);

  virtual void Idb6_eca (Ptr<Tuple> eRuleQuery);

  virtual void Idb7_eca (Ptr<Tuple> rReturn);

  virtual void Idb8Eca0Ins (Ptr<Tuple> pResultTmp);

  virtual void Idb8Eca1Ins (Ptr<Tuple> pQList);

  virtual void Idb9a_eca (Ptr<Tuple> ePReturn);

  virtual void Rv1_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv2_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv3_eca (Ptr<Tuple> ruleQuery);

  virtual void Rv4_eca (Ptr<Tuple> rIterate);

  virtual void Rv5_eca (Ptr<Tuple> rIterate);

  virtual void Rv6_eca (Ptr<Tuple> eProvQuery);

  virtual void Rv7_eca (Ptr<Tuple> pReturn);

  virtual void Rv8Eca0Ins (Ptr<Tuple> rResultTmp);

  virtual void Rv8Eca1Ins (Ptr<Tuple> rQList);

  virtual void Rv9_eca (Ptr<Tuple> eRReturn);

};

} // namespace hypertextclass
} // namespace rapidnet
} // namespace ns3

#endif // HYPERTEXTCLASS_H
